import { SheetTabSchema } from "./types";

export const NESTA_SHEET_SCHEMAS: SheetTabSchema[] = [
  {
    tabName: "Companies",
    entityName: "company",
    idField: "company_id",
    columns: [
      { key: "company_id", label: "معرف الشركة", type: "string", isId: true, required: true },
      { key: "name", label: "اسم الشركة", type: "string", required: true },
      { key: "code", label: "رمز الشركة", type: "string", required: true },
      { key: "targetMonthlySales", label: "هدف المبيعات الشهري", type: "number" },
      { key: "targetMonthlyDeals", label: "هدف الصفقات الشهري", type: "number" },
      { key: "createdAt", label: "تاريخ الإنشاء", type: "date", required: true },
      { key: "updatedAt", label: "تاريخ آخر تحديث", type: "date", required: true },
      { key: "version", label: "رقم الإصدار", type: "number", required: true },
    ],
  },
  {
    tabName: "Users",
    entityName: "user",
    idField: "user_id",
    columns: [
      { key: "user_id", label: "معرف المستخدم", type: "string", isId: true, required: true },
      { key: "company_id", label: "معرف الشركة", type: "string", required: true },
      { key: "name", label: "اسم المستخدم", type: "string", required: true },
      { key: "phone", label: "رقم الهاتف", type: "string" },
      { key: "role", label: "الدور والصلاحية", type: "string", required: true },
      { key: "salesTarget", label: "الهدف البيعي", type: "number" },
      { key: "createdAt", label: "تاريخ الإنشاء", type: "date", required: true },
      { key: "updatedAt", label: "تاريخ آخر تحديث", type: "date", required: true },
      { key: "version", label: "رقم الإصدار", type: "number", required: true },
    ],
  },
  {
    tabName: "Products",
    entityName: "product",
    idField: "product_id",
    columns: [
      { key: "product_id", label: "معرف المنتج", type: "string", isId: true, required: true },
      { key: "company_id", label: "معرف الشركة", type: "string", required: true },
      { key: "name", label: "اسم المنتج", type: "string", required: true },
      { key: "category", label: "فئة المنتج", type: "string", required: true },
      { key: "type", label: "نوع ونظام الفتح", type: "string" },
      { key: "specifications", label: "المواصفات الفنية", type: "string" },
      { key: "unit", label: "وحدة القياس", type: "string" },
      { key: "price", label: "سعر الوحدة الافتراضي", type: "number", required: true },
      { key: "cost", label: "تكلفة الوحدة التقريبية", type: "number" },
      { key: "status", label: "حالة المنتج", type: "string", required: true },
      { key: "createdAt", label: "تاريخ الإنشاء", type: "date", required: true },
      { key: "updatedAt", label: "تاريخ آخر تحديث", type: "date", required: true },
      { key: "version", label: "رقم الإصدار", type: "number", required: true },
    ],
  },
  {
    tabName: "Customers",
    entityName: "customer",
    idField: "customer_id",
    columns: [
      { key: "customer_id", label: "معرف العميل", type: "string", isId: true, required: true },
      { key: "company_id", label: "معرف الشركة", type: "string", required: true },
      { key: "name", label: "اسم العميل", type: "string", required: true },
      { key: "phone", label: "رقم الموبايل", type: "string", required: true },
      { key: "phone2", label: "هاتف بديل", type: "string" },
      { key: "area", label: "المنطقة / المحافظة", type: "string" },
      { key: "source", label: "مصدر العميل", type: "string" },
      { key: "stage", label: "المرحلة الحالية", type: "string", required: true },
      { key: "status", label: "حالة العميل", type: "string", required: true },
      { key: "notes", label: "ملاحظات", type: "string" },
      { key: "totalQuotationsValue", label: "إجمالي عروض الأسعار", type: "number" },
      { key: "totalSalesValue", label: "إجمالي المبيعات", type: "number" },
      { key: "createdAt", label: "تاريخ الإنشاء", type: "date", required: true },
      { key: "updatedAt", label: "تاريخ آخر تحديث", type: "date", required: true },
      { key: "version", label: "رقم الإصدار", type: "number", required: true },
    ],
  },
  {
    tabName: "Inquiries",
    entityName: "inquiry",
    idField: "inquiry_id",
    columns: [
      { key: "inquiry_id", label: "معرف الاستفسار", type: "string", isId: true, required: true },
      { key: "company_id", label: "معرف الشركة", type: "string", required: true },
      { key: "customer_id", label: "معرف العميل", type: "string", required: true },
      { key: "customerName", label: "اسم العميل", type: "string", required: true },
      { key: "customerPhone", label: "هاتف العميل", type: "string" },
      { key: "productType", label: "نوع المنتج / القطاع", type: "string", required: true },
      { key: "dimensions", label: "المقاسات والتوصيف", type: "string" },
      { key: "area", label: "المنطقة", type: "string" },
      { key: "status", label: "حالة الاستفسار", type: "string", required: true },
      { key: "date", label: "تاريخ الاستفسار", type: "date", required: true },
      { key: "notes", label: "ملاحظات", type: "string" },
      { key: "createdAt", label: "تاريخ الإنشاء", type: "date", required: true },
      { key: "updatedAt", label: "تاريخ آخر تحديث", type: "date", required: true },
      { key: "version", label: "رقم الإصدار", type: "number", required: true },
    ],
  },
  {
    tabName: "FollowUps",
    entityName: "followup",
    idField: "followup_id",
    columns: [
      { key: "followup_id", label: "معرف المتابعة", type: "string", isId: true, required: true },
      { key: "company_id", label: "معرف الشركة", type: "string", required: true },
      { key: "customer_id", label: "معرف العميل", type: "string", required: true },
      { key: "customerName", label: "اسم العميل", type: "string", required: true },
      { key: "customerPhone", label: "هاتف العميل", type: "string" },
      { key: "title", label: "عنوان المتابعة", type: "string", required: true },
      { key: "dueDate", label: "تاريخ الاستحقاق", type: "date", required: true },
      { key: "dueTime", label: "وقت المتابعة", type: "string" },
      { key: "priority", label: "الأولوية", type: "string" },
      { key: "status", label: "حالة المتابعة", type: "string", required: true },
      { key: "responsible", label: "المسؤول", type: "string" },
      { key: "notes", label: "تفاصيل المتابعة", type: "string" },
      { key: "createdAt", label: "تاريخ الإنشاء", type: "date", required: true },
      { key: "updatedAt", label: "تاريخ آخر تحديث", type: "date", required: true },
      { key: "version", label: "رقم الإصدار", type: "number", required: true },
    ],
  },
  {
    tabName: "Opportunities",
    entityName: "opportunity",
    idField: "opportunity_id",
    columns: [
      { key: "opportunity_id", label: "معرف الفرصة", type: "string", isId: true, required: true },
      { key: "company_id", label: "معرف الشركة", type: "string", required: true },
      { key: "customer_id", label: "معرف العميل", type: "string", required: true },
      { key: "customerName", label: "اسم العميل", type: "string", required: true },
      { key: "productType", label: "نوع المنتج", type: "string" },
      { key: "stage", label: "مرحلة الفرصة", type: "string", required: true },
      { key: "status", label: "حالة الفرصة", type: "string", required: true },
      { key: "estimatedValue", label: "القيمة التقديرية", type: "number" },
      { key: "priority", label: "الأولوية", type: "string" },
      { key: "assignedTo", label: "المسؤول", type: "string" },
      { key: "lossReason", label: "سبب الخسارة إن وجد", type: "string" },
      { key: "createdAt", label: "تاريخ الإنشاء", type: "date", required: true },
      { key: "updatedAt", label: "تاريخ آخر تحديث", type: "date", required: true },
      { key: "version", label: "رقم الإصدار", type: "number", required: true },
    ],
  },
  {
    tabName: "Quotations",
    entityName: "quotation",
    idField: "quotation_id",
    columns: [
      { key: "quotation_id", label: "معرف عرض السعر", type: "string", isId: true, required: true },
      { key: "company_id", label: "معرف الشركة", type: "string", required: true },
      { key: "customer_id", label: "معرف العميل", type: "string", required: true },
      { key: "customerName", label: "اسم العميل", type: "string", required: true },
      { key: "quoteNumber", label: "رقم العرض", type: "string", required: true },
      { key: "date", label: "تاريخ العرض", type: "date", required: true },
      { key: "status", label: "حالة العرض", type: "string", required: true },
      { key: "subtotal", label: "المبلغ الإجمالي", type: "number" },
      { key: "discountTotal", label: "الخصم", type: "number" },
      { key: "totalAmount", label: "الصافي النهائي", type: "number", required: true },
      { key: "profileType", label: "نوع القطاع", type: "string" },
      { key: "glassType", label: "نوع الزجاج", type: "string" },
      { key: "notes", label: "ملاحظات وشروط", type: "string" },
      { key: "createdAt", label: "تاريخ الإنشاء", type: "date", required: true },
      { key: "updatedAt", label: "تاريخ آخر تحديث", type: "date", required: true },
      { key: "version", label: "رقم الإصدار", type: "number", required: true },
    ],
  },
  {
    tabName: "Inspections",
    entityName: "inspection",
    idField: "inspection_id",
    columns: [
      { key: "inspection_id", label: "معرف المعاينة", type: "string", isId: true, required: true },
      { key: "company_id", label: "معرف الشركة", type: "string", required: true },
      { key: "customer_id", label: "معرف العميل", type: "string", required: true },
      { key: "customerName", label: "اسم العميل", type: "string", required: true },
      { key: "date", label: "تاريخ المعاينة", type: "date", required: true },
      { key: "time", label: "وقت المعاينة", type: "string" },
      { key: "address", label: "العنوان / الموقع", type: "string" },
      { key: "surveyor", label: "الفني المعاين", type: "string" },
      { key: "result", label: "نتيجة المعاينة", type: "string", required: true },
      { key: "measurementsCount", label: "عدد الفتحات / المقاسات", type: "number" },
      { key: "notes", label: "ملاحظات المعاينة", type: "string" },
      { key: "createdAt", label: "تاريخ الإنشاء", type: "date", required: true },
      { key: "updatedAt", label: "تاريخ آخر تحديث", type: "date", required: true },
      { key: "version", label: "رقم الإصدار", type: "number", required: true },
    ],
  },
  {
    tabName: "Contracts",
    entityName: "contract",
    idField: "contract_id",
    columns: [
      { key: "contract_id", label: "معرف العقد", type: "string", isId: true, required: true },
      { key: "company_id", label: "معرف الشركة", type: "string", required: true },
      { key: "customer_id", label: "معرف العميل", type: "string", required: true },
      { key: "customerName", label: "اسم العميل", type: "string", required: true },
      { key: "contractNumber", label: "رقم العقد", type: "string", required: true },
      { key: "date", label: "تاريخ التعاقد", type: "date", required: true },
      { key: "deliveryDate", label: "تاريخ التوريد المتوقع", type: "date" },
      { key: "totalValue", label: "قيمة العقد الإجمالية", type: "number", required: true },
      { key: "paidAmount", label: "المسدد", type: "number", required: true },
      { key: "remainingAmount", label: "المتبقي", type: "number", required: true },
      { key: "status", label: "حالة العقد", type: "string", required: true },
      { key: "collectionStatus", label: "مرحلة التحصيل", type: "string" },
      { key: "createdAt", label: "تاريخ الإنشاء", type: "date", required: true },
      { key: "updatedAt", label: "تاريخ آخر تحديث", type: "date", required: true },
      { key: "version", label: "رقم الإصدار", type: "number", required: true },
    ],
  },
  {
    tabName: "Sales",
    entityName: "sale",
    idField: "sale_id",
    columns: [
      { key: "sale_id", label: "معرف سجل البيع", type: "string", isId: true, required: true },
      { key: "company_id", label: "معرف الشركة", type: "string", required: true },
      { key: "customer_id", label: "معرف العميل", type: "string" },
      { key: "customerName", label: "اسم العميل", type: "string", required: true },
      { key: "contractId", label: "معرف العقد", type: "string" },
      { key: "contractNumber", label: "رقم العقد", type: "string" },
      { key: "amount", label: "قيمة البيع", type: "number", required: true },
      { key: "date", label: "تاريخ البيع", type: "date", required: true },
      { key: "responsible", label: "المسؤول / البائع", type: "string" },
      { key: "customerSource", label: "مصدر العميل", type: "string" },
      { key: "area", label: "المنطقة", type: "string" },
      { key: "notes", label: "ملاحظات", type: "string" },
      { key: "createdAt", label: "تاريخ الإنشاء", type: "date", required: true },
      { key: "updatedAt", label: "تاريخ آخر تحديث", type: "date", required: true },
      { key: "version", label: "رقم الإصدار", type: "number", required: true },
    ],
  },
  {
    tabName: "Collections",
    entityName: "collection",
    idField: "collection_id",
    columns: [
      { key: "collection_id", label: "معرف الدفعة", type: "string", isId: true, required: true },
      { key: "company_id", label: "معرف الشركة", type: "string", required: true },
      { key: "customer_id", label: "معرف العميل", type: "string", required: true },
      { key: "contractId", label: "معرف العقد", type: "string", required: true },
      { key: "amount", label: "المبلغ المحصل", type: "number", required: true },
      { key: "date", label: "تاريخ التحصيل", type: "date", required: true },
      { key: "paymentMethod", label: "طريقة الدفع", type: "string" },
      { key: "receiptNumber", label: "رقم الإيصال", type: "string" },
      { key: "collector", label: "المحصل", type: "string" },
      { key: "notes", label: "ملاحظات", type: "string" },
      { key: "createdAt", label: "تاريخ الإنشاء", type: "date", required: true },
      { key: "updatedAt", label: "تاريخ آخر تحديث", type: "date", required: true },
      { key: "version", label: "رقم الإصدار", type: "number", required: true },
    ],
  },
  {
    tabName: "Sync_Log",
    entityName: "sync_log",
    idField: "log_id",
    columns: [
      { key: "log_id", label: "معرف السجل", type: "string", isId: true, required: true },
      { key: "timestamp", label: "التاريخ والوقت", type: "date", required: true },
      { key: "direction", label: "اتجاه المزامنة", type: "string", required: true },
      { key: "entity", label: "الكيان", type: "string", required: true },
      { key: "record_id", label: "معرف السجل المرتبط", type: "string", required: true },
      { key: "company_id", label: "معرف الشركة", type: "string", required: true },
      { key: "status", label: "الحالة", type: "string", required: true },
      { key: "changes_summary", label: "ملخص التغييرات", type: "string", required: true },
      { key: "error_message", label: "رسالة الخطأ إن وجدت", type: "string" },
    ],
  },
  {
    tabName: "Sync_Conflicts",
    entityName: "sync_conflict",
    idField: "conflict_id",
    columns: [
      { key: "conflict_id", label: "معرف التعارض", type: "string", isId: true, required: true },
      { key: "entity", label: "الكيان", type: "string", required: true },
      { key: "record_id", label: "معرف السجل", type: "string", required: true },
      { key: "company_id", label: "معرف الشركة", type: "string", required: true },
      { key: "timestamp", label: "وقت اكتشاف التعارض", type: "date", required: true },
      { key: "nesta_version", label: "إصدار NESTA", type: "number", required: true },
      { key: "nesta_data", label: "بيانات NESTA (JSON)", type: "json", required: true },
      { key: "sheets_version", label: "إصدار Sheets", type: "number", required: true },
      { key: "sheets_data", label: "بيانات Sheets (JSON)", type: "json", required: true },
      { key: "status", label: "حالة التعارض", type: "string", required: true },
      { key: "resolved_by", label: "تم الحل بواسطة", type: "string" },
      { key: "resolution_notes", label: "ملاحظات الحل", type: "string" },
    ],
  },
  {
    tabName: "System_Metadata",
    entityName: "metadata",
    idField: "key",
    columns: [
      { key: "key", label: "المفتاح", type: "string", isId: true, required: true },
      { key: "value", label: "القيمة", type: "string", required: true },
      { key: "updatedAt", label: "تاريخ التحديث", type: "date", required: true },
      { key: "description", label: "الوصف", type: "string" },
    ],
  },
];
